### ISSUE TITLE
How to use other lidar sensors to run this project?

### ISSUE THREAD

**Issue by akamob** [sieuwe1/Autonomous-Ai-drone-scripts#5]
Hi, Thank you for the awesome work.

I want to use your work on my quadcopter with a VLP-16 lidar, we use VLP-16 for detection and slam.

Can you give me some suggestions to modify the code to suit 3D lidar?

Any help is much appreciated:)

**Comment by sieuwe1** [comment]
Hi,

If you want to use the person following script with VLP-16 you need to change the code. We use a solid state lidar meaning it only outputs one single point. So if you want to use VLP-16 lidar I suggest you filter out all points except for the points at 0 degree so point exact at the front of the drone. Also I suggest disabling all layers except one layer so you have a couple points only straight in front of the drone. Then just take average of these couple points and give this as value to our program. 

But since your lider has much more info you throw away with this method I suggest you might look into having the lidar and rgb image alligned with each other. And then match the detection in rgb with point cloud points in the lidaer point cloud. This should give much better tracking in depth axis. 

Greetings 

Sieuwe

**Comment by akamob** [comment]
Thank you very much for your reply:)

I will try to test.
